name: Bonjour

on: [push] # Ce workflow se déclenche sur un push dans le dépôt

jobs:
  Salutations: # Nom du job
    name: Salutations
    runs-on: ubuntu-latest # OS où s'exécute le job
    steps:
      - name: Hello # Une tâche pour saluer
        env:
          personneASaluer: 'Mon voisin Totoro'
        run: echo "Bonjour \"

      - name: L'heure de salutation # Affiche l'heure de la précédente tâche
        run: echo "L'heure était \09/17/2025 10:57:37."
